baseurl = "/"
# If you use "hugo server" you might want to use this entry:
# baseurl = "http://localhost:1313/"
title = "Power Query for Accountants"
copyright = "Â© 2019 Power Query for Accountants"
canonifyurls = true
paginate = 3
theme = "jeffprod"


[taxonomies]
  tag = "tags"
  archive = "archives"